### ISSUE TITLE
greate performance degradation

### ISSUE THREAD

**Issue by hellpain** [iron/iron#396] opened 2015-10-14 22:59 UTC
I decided to repeat wrk test for helloworld from documentation on my computer.
I had rust 1.2 and such result:
>wrk -t12 -c900 -d10s http://127.0.0.1:3000/
Running 10s test @ http://127.0.0.1:3000/
  12 threads and 900 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   170.13us  113.36us   6.43ms   92.11%
    Req/Sec    18.21k     2.24k   22.49k    73.27%
  182872 requests in 10.08s, 19.88MB read
  Socket errors: connect 0, read 0, write 0, timeout 2
Requests/sec:  18145.14
Transfer/sec:      1.97MB

18k RPS - not bad.

Than I decided to uprade rust to 1.3 and compare performance. Also I deleted Cargo.lock to get the latest version of packets. Now a have very bad performance:
>wrk -t12 -c900 -d10s http://127.0.0.1:3000/                     
Running 10s test @ http://127.0.0.1:3000/
  12 threads and 900 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    30.76ms   42.62ms 218.86ms   95.56%
    Req/Sec   155.19    172.17   604.00     80.77%
  901 requests in 10.07s, 100.31KB read
  Socket errors: connect 0, read 1, write 0, timeout 0
Requests/sec:     89.45
Transfer/sec:      9.96KB

89 RPS? What did happen?
My current Cargo.lock:
[root]
name = "web_server"
version = "0.1.0"
dependencies = [
 "iron 0.2.2 (registry+https://github.com/rust-lang/crates.io-index)",
 "time 0.1.32 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "advapi32-sys"
version = "0.1.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "winapi 0.2.4 (registry+https://github.com/rust-lang/crates.io-index)",
 "winapi-build 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "bitflags"
version = "0.3.2"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "conduit-mime-types"
version = "0.7.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "rustc-serialize 0.3.16 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "cookie"
version = "0.1.21"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "openssl 0.6.6 (registry+https://github.com/rust-lang/crates.io-index)",
 "rustc-serialize 0.3.16 (registry+https://github.com/rust-lang/crates.io-index)",
 "time 0.1.32 (registry+https://github.com/rust-lang/crates.io-index)",
 "url 0.2.37 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "error"
version = "0.1.7"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "traitobject 0.0.3 (registry+https://github.com/rust-lang/crates.io-index)",
 "typeable 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "gcc"
version = "0.3.18"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "advapi32-sys 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)",
 "winapi 0.2.4 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "hpack"
version = "0.2.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "log 0.3.2 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "httparse"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "hyper"
version = "0.6.15"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "cookie 0.1.21 (registry+https://github.com/rust-lang/crates.io-index)",
 "httparse 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "language-tags 0.0.7 (registry+https://github.com/rust-lang/crates.io-index)",
 "log 0.3.2 (registry+https://github.com/rust-lang/crates.io-index)",
 "mime 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "num_cpus 0.2.6 (registry+https://github.com/rust-lang/crates.io-index)",
 "openssl 0.6.6 (registry+https://github.com/rust-lang/crates.io-index)",
 "rustc-serialize 0.3.16 (registry+https://github.com/rust-lang/crates.io-index)",
 "solicit 0.4.4 (registry+https://github.com/rust-lang/crates.io-index)",
 "time 0.1.32 (registry+https://github.com/rust-lang/crates.io-index)",
 "traitobject 0.0.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "typeable 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)",
 "unicase 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "url 0.2.37 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "iron"
version = "0.2.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "conduit-mime-types 0.7.3 (registry+https://github.com/rust-lang/crates.io-index)",
 "error 0.1.7 (registry+https://github.com/rust-lang/crates.io-index)",
 "hyper 0.6.15 (registry+https://github.com/rust-lang/crates.io-index)",
 "lazy_static 0.1.15 (registry+https://github.com/rust-lang/crates.io-index)",
 "log 0.3.2 (registry+https://github.com/rust-lang/crates.io-index)",
 "modifier 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "num_cpus 0.2.6 (registry+https://github.com/rust-lang/crates.io-index)",
 "plugin 0.2.6 (registry+https://github.com/rust-lang/crates.io-index)",
 "typemap 0.3.3 (registry+https://github.com/rust-lang/crates.io-index)",
 "url 0.2.37 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "kernel32-sys"
version = "0.1.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "winapi 0.2.4 (registry+https://github.com/rust-lang/crates.io-index)",
 "winapi-build 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "language-tags"
version = "0.0.7"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "lazy_static"
version = "0.1.15"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "libc"
version = "0.1.10"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "libressl-pnacl-sys"
version = "2.1.6"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "pnacl-build-helper 1.4.10 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "log"
version = "0.3.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "libc 0.1.10 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "matches"
version = "0.1.2"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "mime"
version = "0.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "log 0.3.2 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "modifier"
version = "0.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "num_cpus"
version = "0.2.6"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "libc 0.1.10 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "openssl"
version = "0.6.6"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "bitflags 0.3.2 (registry+https://github.com/rust-lang/crates.io-index)",
 "lazy_static 0.1.15 (registry+https://github.com/rust-lang/crates.io-index)",
 "libc 0.1.10 (registry+https://github.com/rust-lang/crates.io-index)",
 "openssl-sys 0.6.6 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "openssl-sys"
version = "0.6.6"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "gcc 0.3.18 (registry+https://github.com/rust-lang/crates.io-index)",
 "libc 0.1.10 (registry+https://github.com/rust-lang/crates.io-index)",
 "libressl-pnacl-sys 2.1.6 (registry+https://github.com/rust-lang/crates.io-index)",
 "pkg-config 0.3.6 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "pkg-config"
version = "0.3.6"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "plugin"
version = "0.2.6"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "typemap 0.3.3 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "pnacl-build-helper"
version = "1.4.10"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "tempdir 0.3.4 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "rand"
version = "0.3.11"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "advapi32-sys 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)",
 "libc 0.1.10 (registry+https://github.com/rust-lang/crates.io-index)",
 "winapi 0.2.4 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "rustc-serialize"
version = "0.3.16"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "solicit"
version = "0.4.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "hpack 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "log 0.3.2 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "tempdir"
version = "0.3.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "rand 0.3.11 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "time"
version = "0.1.32"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "kernel32-sys 0.1.4 (registry+https://github.com/rust-lang/crates.io-index)",
 "libc 0.1.10 (registry+https://github.com/rust-lang/crates.io-index)",
 "winapi 0.2.4 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "traitobject"
version = "0.0.1"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "traitobject"
version = "0.0.3"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "typeable"
version = "0.1.2"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "typemap"
version = "0.3.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "unsafe-any 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "unicase"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "unsafe-any"
version = "0.4.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "traitobject 0.0.3 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "url"
version = "0.2.37"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "matches 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)",
 "rustc-serialize 0.3.16 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "winapi"
version = "0.2.4"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "winapi-build"
version = "0.1.1"
source = "registry+https://github.com/rust-lang/crates.io-index"

**Comment by reem** [comment] 2015-10-14 23:09
@hellpain can you include the full series of commands you used to get that result (preferably from git clone onwards) so I can try to reproduce it locally?

**Comment by hellpain** [comment] 2015-10-15 09:08
cargo new hello_world --bin
edit main.rs as here https://github.com/iron/iron/blob/master/examples/hello.rs
add to Cargo.toml
> [dependencies.iron]
version = "*"

cargo clean
cargo build --release
./target/release/hello_world

Then in second terminal I start wrk:
wrk -t12 -c900 -d10s http://127.0.0.1:3000/

I think you will be able to reproduce this, if you delete Cargo.lock and let cargo download latest versions of packets. I suppose this bug in some external library, not in Iron. Unfortunately, I can`t recover old Cargo.lock, where I had good performance.
I also repeated it on my notebook on clean system - 93 RPS.

**Comment by meowy** [comment] 2015-10-18 22:42
Can replicate according to @hellpain's instructions with `rustc 1.3.0 (9a92aaf19 2015-09-15)`:

    Running 10s test @ http://[::1]:3000/
      12 threads and 900 connections
      Thread Stats   Avg      Stdev     Max   +/- Stdev
        Latency    11.56ms   38.23ms 203.58ms   96.15%
        Req/Sec    61.75     96.61   368.00     82.81%
      909 requests in 10.10s, 101.20KB read
      Socket errors: connect 0, read 9, write 0, timeout 0
    Requests/sec:     89.98
    Transfer/sec:     10.02KB

The same goes for `rustc 1.5.0-nightly (32a8567ea 2015-10-05)`:

    Running 10s test @ http://[::1]:3000/
      12 threads and 900 connections
      Thread Stats   Avg      Stdev     Max   +/- Stdev
        Latency    60.29ms   87.60ms 400.79ms   72.71%
        Req/Sec   127.51    158.74   714.00     89.74%
      905 requests in 10.08s, 100.75KB read
      Socket errors: connect 0, read 5, write 0, timeout 0
    Requests/sec:     89.74
    Transfer/sec:      9.99KB

Running Linux kernel 4.2.2-1-ARCH.

**Comment by meowy** [comment] 2015-10-18 22:46
Unsurprisingly, it doesn't seem to matter whether the Iron server is bound to IPv4 or IPv6.

**Comment by meowy** [comment] 2015-10-18 22:57
Issue seems to be upstream in [hyper](https://github.com/hyperium/hyper).

**Comment by reem** [comment] 2015-10-18 23:11
I can reproduce as well, though my perf is more like 8k req/sec. I think this is likely due to hyper turning off keep-alive by default, which would substantially degrade performance in a benchmark like wrk.

Iron could turn keep-alive back on by default to solve this problem, improving perf in benchmarks but bringing back the demons of https://github.com/hyperium/hyper/issues/368.

**Comment by meowy** [comment] 2015-10-18 23:29
Actually, I can't replicate this in pure Hyper with `rustc 1.3.0 (9a92aaf19 2015-09-15)` and hyper 0.6.15 - the version latest Iron depends on - using the [hello world server in the README](https://github.com/hyperium/hyper#hello-world-server).

**Comment by hellpain** [comment] 2015-10-19 08:38
@meowy On your hello-world I have 19k RPS instead of 19 on mine=)

**Comment by badboy** [comment] 2015-10-24 15:50
I have the same degradation with 1.3 and nightly: only ~90 requests/sec using the iron hello example.

Problematic:
```
rustc 1.5.0-nightly (7beebbe56 2015-10-22)
rustc 1.3.0 (9a92aaf19 2015-09-15)
```

**Comment by veegee** [comment] 2015-11-05 05:37
Same issue. What's going on here?

**Comment by hellpain** [comment] 2015-11-05 08:28
@meowy Is there any way to fix keep-alive connections?

**Comment by dariusc93** [comment] 2015-11-05 21:29
Is this even still a problem?

**Comment by veegee** [comment] 2015-11-05 22:48
@dariusc93 very much so. When I set up the latest versions of all packages, with rust 1.4, I only get ~10 req/s with wrk.

**Comment by dariusc93** [comment] 2015-11-06 14:21
@veegee does it show that many when you use ab?

**Comment by veegee** [comment] 2015-11-07 04:45
@dariusc93 interesting, `ab` gives me the following:

```
➜ ab -n 100000 -c 100 127.0.0.1:8001/
This is ApacheBench, Version 2.3 <$Revision: 1638069 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 10000 requests
Completed 20000 requests
Completed 30000 requests
Completed 40000 requests
Completed 50000 requests
Completed 60000 requests
Completed 70000 requests
Completed 80000 requests
Completed 90000 requests
Completed 100000 requests
Finished 100000 requests


Server Software:
Server Hostname:        127.0.0.1
Server Port:            8001

Document Path:          /
Document Length:        12 bytes

Concurrency Level:      100
Time taken for tests:   4.926 seconds
Complete requests:      100000
Failed requests:        0
Total transferred:      11400000 bytes
HTML transferred:       1200000 bytes
Requests per second:    20300.88 [#/sec] (mean)
Time per request:       4.926 [ms] (mean)
Time per request:       0.049 [ms] (mean, across all concurrent requests)
Transfer rate:          2260.06 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        1    2   0.2      2       4
Processing:     1    3   0.7      3      25
Waiting:        1    2   0.7      2      24
Total:          3    5   0.6      5      27

Percentage of the requests served within a certain time (ms)
  50%      5
  66%      5
  75%      5
  80%      5
  90%      6
  95%      6
  98%      6
  99%      6
 100%     27 (longest request)
```

**Comment by Antti** [comment] 2015-12-01 17:16
Updated crates, now performance is back to normal (Requests/sec:  80339.57)

Crates updated:
```
    Updating cookie v0.1.21 -> v0.2.2
    Updating gcc v0.3.19 -> v0.3.20
    Updating hyper v0.6.16 -> v0.7.0
    Updating iron v0.2.4 -> v0.2.5
    Updating language-tags v0.0.7 -> v0.2.0
    Removing libc v0.1.12
    Updating log v0.3.3 -> v0.3.4
    Updating num_cpus v0.2.9 -> v0.2.10
    Updating openssl v0.6.7 -> v0.7.1
    Updating openssl-sys v0.6.7 -> v0.7.1
      Adding openssl-sys-extras v0.7.1
    Updating url v0.2.38 -> v0.5.0
```

I suspect it was hyper update, which fixed the regression.

**Comment by untitaker** [comment] 2015-12-01 18:08
Shall we close this then?

On 1 December 2015 18:16:07 CET, Andrii Dmytrenko <notifications@github.com> wrote:
>Updated crates, now performance is back to normal (Requests/sec: 
>80339.57)
>
>Crates updated:
>```
>    Updating cookie v0.1.21 -> v0.2.2
>    Updating gcc v0.3.19 -> v0.3.20
>    Updating hyper v0.6.16 -> v0.7.0
>    Updating iron v0.2.4 -> v0.2.5
>    Updating language-tags v0.0.7 -> v0.2.0
>    Removing libc v0.1.12
>    Updating log v0.3.3 -> v0.3.4
>    Updating num_cpus v0.2.9 -> v0.2.10
>    Updating openssl v0.6.7 -> v0.7.1
>    Updating openssl-sys v0.6.7 -> v0.7.1
>      Adding openssl-sys-extras v0.7.1
>    Updating url v0.2.38 -> v0.5.0
>```
>
>I suspect it was hyper update, which fixed the regression.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/iron/iron/issues/396#issuecomment-161037258

-- 
Sent from my phone. Please excuse my brevity.

**Comment by dariusc93** [comment] 2015-12-01 18:22
Is there a specific commit that couldve fixed this?

**Comment by hellpain** [comment] 2015-12-01 21:14
> wrk -t12 -c900 -d10s http://localhost:3000/
Running 10s test @ http://localhost:3000/
  12 threads and 900 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   180.63us  139.77us  13.53ms   93.58%
    Req/Sec    20.15k     1.67k   22.99k    77.23%
  202211 requests in 10.09s, 21.98MB read
Requests/sec:  20047.55
Transfer/sec:      2.18MB

Speed is even better on 2k RPS then in my first post on the same computer. Thanks all.
Issue can be closed.

**Comment by sovereignsoftware** [comment] 2015-12-01 21:15
I wouldn't consider it completely fixed. I'm having two issues with performance still. With `wrk` it performs well now, but with `wrk2` it falters and times out 2/3 of requests. The difference between the two is that `wrk2` tries to force-feed a given throughput level to the server:

    > wrk2 -t4 -c10000 -d60s -R 1000000 http://localhost:3000/
    Running 1m test @ http://localhost:3000/
      4 threads and 10000 connections
      Thread calibration: mean lat.: 6.798ms, rate sampling interval: 10ms
      Thread calibration: mean lat.: 9223372036854776.000ms, rate sampling interval: 10ms
      Thread calibration: mean lat.: 1.049ms, rate sampling interval: 10ms
      Thread calibration: mean lat.: 9223372036854776.000ms, rate sampling interval: 10ms
      Thread Stats   Avg      Stdev     Max   +/- Stdev
        Latency     0.95ms  495.12us  23.30ms   68.01%
        Req/Sec   679.49    692.42     2.22k    77.23%
      155888 requests in 1.01m, 21.26MB read
      Socket errors: connect 8983, read 0, write 0, timeout 234398
    Requests/sec:   2575.48
    Transfer/sec:    359.66KB

The same benchmark with Scala's http4s, for example, will handle 66k req/s on the same machine with the same test but the latency numbers will be expectedly through the roof. I find that after running either `wrk` or `wrk2`, the server is "stuck" for a while and won't handle any new requests made from my browser until I guess the timeouts expire.

**Comment by untitaker** [comment] 2015-12-03 12:18
I strongly suspect that this has something to do with keepalive-support being reenabled. Are there noticable differences in performance if you don't make any use of keepalive?

**Comment by dariusc93** [comment] 2015-12-03 14:35
Why not put your application behind something like nginx or haproxy? (you can do this in a container as well if you dont want it directly on your system)

**Comment by Antti** [comment] 2015-12-15 13:50
@sovereignsoftware didn't we have this problem all the time?

**Comment by reem** [comment] 2016-02-22 04:13
I believe this is basically fixed by turning hyper keep alive back on by default.

**Closed by reem** 2016-02-22 04:13 UTC
