### ISSUE TITLE
For some reason, Cargo returns "thread '<main>' has overflowed its stack"

### ISSUE THREAD

**Issue by moenad** [iron/iron#376] opened 2015-08-20 02:30 UTC
I tried multiple dependencies but each time I add Iron, I get the error mentioned in the title.

I'm on a mac, and I'm using Rustc 1.2.0 and cargo 0.4.0.

I'm new to Rust in general, and I was looking forward to try Iron. No luck so far.

**Comment by reem** [comment] 2015-08-20 05:14
Hmm, can you post some context, like your Cargo.toml or other code? I am having trouble reproducing this locally.

**Comment by moenad** [comment] 2015-08-20 08:06
If I create a new project with `cargo new` and I simply edit the cargo.toml file adding to it

```
[dependencies.iron]
version = "*"
````

or

```
[dependencies]
  2 iron = "*"
```

 and I try to  `generate-lockfile`, `build`.... I get the following:

> Updating registry `https://github.com/rust-lang/crates.io-index`

> thread '<main>' has overflowed its stack
> [1]    71643 illegal hardware instruction  cargo build

Rust is installed using brew.

**Comment by Mange** [comment] 2015-09-03 17:49
You need to reinstall with the latest `HEAD`.

```
brew uninstall rust
brew update
vim  /usr/local/Library/Formula/rust.rb # Comment out the part about patching "Makefile.in", or the build will fail
brew install --HEAD rust
```

This worked for me today, 2015-09-03. `cargo` was patched 4 days ago, but Homebrew does not have the new version of `cargo` in the formula. I trust this will be solved in time.

**Comment by Mange** [comment] 2015-09-03 18:10
Actually, that might also be a bad idea. I can't compile the examples because of strange compiler errors. Maybe `master` is broken, maybe it's not compatible with latest `iron` version, maybe both.

So I either install a broken version of Rust (or rather Cargo), or I install a version of Rust that cannot compile Iron `master` or Iron samples with latest cargo release.

**Comment by reem** [comment] 2015-09-04 04:28
Sorry, I can't reproduce this locally with either the latest stable cargo and rustc or the latest nightly, could you try upgrading and seeing if that solves your problem?.

**Comment by untitaker** [comment] 2015-10-18 21:50
is this still an issue?

**Comment by untitaker** [comment] 2015-10-27 20:40
Closing because this is neither reproducible nor an active thread.

**Closed by untitaker** 2015-10-27 20:40 UTC
Labels: closing candidate
