### ISSUE TITLE
https / malloc: *** error for object ... pointer being freed was not allocated

### ISSUE THREAD

**Issue by xpe** [iron/iron#463] opened 2016-06-12 07:51 UTC
I don't know for sure if this is caused by Iron, but I'll share what I know about my error.

My "Cargo.toml" file:

```toml
[package]
name = "my-server"
version = "0.1.0"
authors = ["me"]

[dependencies]
router = "0.1.1"

[dependencies.iron]
version = "0.3.0"
features = ["ssl"]
```

My "main.rs" file:

```rs
extern crate iron;
extern crate router;

use iron::status;
use iron::{Iron, IronResult, Request, Response};
use router::{Router};
use std::path::{Path};
use std::result::{Result};

fn handler(_: &mut Request) -> IronResult<Response> {
    Ok(Response::with((status::Ok, "Hello World!")))
}

fn main() {
    let mut router = Router::new();
    router.get("/foo", handler);
    let cert = Path::new("/Users/myusername/certs/localhost.crt").to_path_buf();
    let key = Path::new("/Users/myusername/certs/localhost.key").to_path_buf();
    match Iron::new(router).https("localhost:3000", cert, key) {
        Result::Ok(listening) => println!("{:?}", listening),
        Result::Err(err) => println!("{:?}", err),
    }
}
```

```
❯ cargo run
     Running `target/debug/my-server`
Listening { socket: V6([::1]:3000) }
```

but at some point, this happens:

```
my-server(19003,0x700000607000) malloc: *** error for object 0x7f80f84044a0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
error: Process didn't exit successfully: `target/debug/my-server` (signal: 6, SIGABRT: process abort signal)
```

Here is how I reproduce the crash... I refresh about five to fifteen times in my web browser pointing to "https://localhost:3000/foo".

I'm not sure what the cause is. It is not obviously the number of requests or a particular length of time, best I can tell.

FWIW, I'm using Homebrew's OpenSSL:

```
❯ brew info openssl
openssl: stable 1.0.2h (bottled) [keg-only]
SSL/TLS cryptography library
https://openssl.org/
/usr/local/Cellar/openssl/1.0.2h_1 (1,691 files, 12M)
  Built from source on 2016-05-16 at 09:55:16
```

Anyone else seeing this?

**Comment by xpe** [comment] 2016-06-12 16:24
I got more information:

```
❯ RUST_BACKTRACE=1 cargo run
     Running `target/debug/my-server`
Listening { socket: V6([::1]:3000) }
my-server(19639,0x700000607000) malloc: *** error for object 0x7f992be036d0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
error: Process didn't exit successfully: `target/debug/my-server` (signal: 6, SIGABRT: process abort signal)
```

**Comment by PlasmaPower** [comment] 2016-09-07 04:40
This error is coming from iron's HTTP library `hyper`, which in turn uses `rust-openssl` for HTTPS. Try to reproduce the issue with a raw `hyper` server, then report it there (it doesn't seem reasonable to reproduce it without hyper, most likely it's due in part to hyper's use of rust-openssl).

**Comment by Hoverbear** [comment] 2016-09-08 10:18
And please link the issue here when you do so we can follow it =D

**Comment by Hoverbear** [comment] 2016-09-30 11:26
I was unable to repo this with the latest versions.

`Cargo.toml`:
```toml
[package]
name = "my-server"
version = "0.1.0"
authors = ["me"]

[dependencies]
router = "0.4.0"

[dependencies.iron]
version = "0.4.0"
features = ["ssl"]
```

`src/main.rs`:
```rust
extern crate iron;
extern crate router;

use iron::status;
use iron::{Iron, IronResult, Request, Response};
use router::{Router};
use std::path::{Path};
use std::result::{Result};

fn handler(_: &mut Request) -> IronResult<Response> {
    println!("Got a request");
    Ok(Response::with((status::Ok, "Hello World!")))
}

fn main() {
    let mut router = Router::new();
    router.get("/foo", handler, "foo");
    // openssl genrsa -out localhost.key 4096
    let key = Path::new("localhost.key").to_path_buf();
    // openssl req -key localhost.key -x509 -new -days 3650 -out cacert.crt
    let cert = Path::new("localhost.crt").to_path_buf();

    match Iron::new(router).https("127.0.0.1:3000", cert, key) {
        Result::Ok(listening) => println!("{:?}", listening),
        Result::Err(err) => println!("{:?}", err),
    }
    // curl -vvvv https://127.0.0.1:3000/foo -k
}
```

Running:

```bash
curl -vvvv https://127.0.0.1:3000/foo -k
```

A bunch as well as loading the URL in my browser many times resulted in no errors:

![screen shot 2016-09-30 at 13 24 49](https://cloud.githubusercontent.com/assets/130903/18990346/761cca4a-8711-11e6-93d2-4ed45ffc006f.png)


Closing since this seems to no longer be an issue.

**Closed by Hoverbear** 2016-09-30 11:26 UTC
