### ISSUE TITLE
URL fragment not being read.

### ISSUE THREAD

**Issue by waqqas-abdulkareem** [iron/iron#337] opened 2015-04-28 19:23 UTC
I'm developing a console-based Facebook application using Rust.

Once the user signs in from the browser, Facebook redirects to a given URL and passes the access token as a URL fragment:

`http://localhost:7000/?#access_token=CAAF.....ZD&expires_in=3943`

When retrieving this fragment from the URL using iron's url implementation, I get an empty string.

```rust
fn fb_token(req: &mut Request)->IronResult<Response>{
        let fragment = match req.url.fragment{
    		Some(ref fragment) => fragment.clone(),
    		None => "".to_string()
    	};

      Ok(Response::with((status::Ok,fragment))); //prints empty string.
}
```

Parsing the url into `servo/rest-url` and then retrieving the fragment yields the desired output.

```rust
let url = url::Url::parse().unwrap("http://localhost:7000/?#access_token=CAAF.....ZD&expires_in=3943");
let fragment = match url.fragment{
    		Some(ref fragment) => fragment.clone(),
    		None => "".to_string()
    	};
Ok(Response::with((status::Ok,fragment))) //prints fragment
```

**Comment by reem** [comment] 2015-05-07 23:08
I looked through the implementation and didn't see anything obvious... @michaelsproul you are probably most familiar with the url implementation - any idea what might be happening here?

**Comment by michaelsproul** [comment] 2015-05-08 01:23
I haven't been able to reproduce this, and according to this test program, Iron and `rust-url` produce the same results:

```rust
extern crate iron;
extern crate url;

use iron::request::Url;

fn main() {
    let url_str = "http://host.com/?#fragment=thing&q1=v1";

    let u = url::Url::parse(url_str).unwrap();
    let i = Url::parse(url_str).unwrap();

    println!("Raw URL parser results:");
    println!("  Query: {:?}", u.query);
    println!("  Fragment: {:?}", u.fragment);

    println!("Iron URL parser results:");
    println!("  Query: {:?}", i.query);
    println!("  Fragment: {:?}", i.fragment);
}
```

Output:

```
Raw URL parser results:
  Query: Some("")
  Fragment: Some("fragment=thing&q1=v1")
Iron URL parser results:
  Query: Some("")
  Fragment: Some("fragment=thing&q1=v1")
```

As you can see, all the data after the `#` gets dumped into the fragment field. This is part of the WHATWG URL spec: https://url.spec.whatwg.org/#query-state

Once the URL parsing state machine enters the fragment state it treats all subsequent characters as part of the the fragment, and there's no way to get back to the query state to parse the `&q1=v1` part.

@waqqas-abdulkareem, could you provide a link to the Facebook API you're dealing with? From my investigations so far it seems they may be returning invalid URLs, or there's some error elsewhere in the pipeline.

**Comment by michaelsproul** [comment] 2015-06-17 13:23
Triage... I think we can close this? @reem @waqqas-abdulkareem

**Comment by reem** [comment] 2015-06-17 19:56
Yup. Closing due to inactivity. Anyone feel free to comment if they can reproduce.

**Closed by reem** 2015-06-17 19:56 UTC
Labels: bug
